"""add device presence snapshots

Revision ID: 577f76d1d3ad
Revises: f77f533a6ec7
Create Date: 2026-02-01 07:42:19.731322

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "577f76d1d3ad"
down_revision = "f77f533a6ec7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_presence_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("ip_address", sa.String(length=15), nullable=True),
        sa.Column("hostname", sa.String(length=100), nullable=True),
        sa.Column("mdns_services", sa.JSON(), nullable=True),
        sa.Column("is_randomized_mac", sa.Boolean(), nullable=True),
        sa.Column("fingerprint_confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("device_presence_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_device_presence_snapshot_device_id"), ["device_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_device_presence_snapshot_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_presence_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_device_presence_snapshot_timestamp"))
        batch_op.drop_index(batch_op.f("ix_device_presence_snapshot_device_id"))

    op.drop_table("device_presence_snapshot")
    # ### end Alembic commands ###
