"""Initial setup migration

Revision ID: a6bb37c31ff9
Revises: 
Create Date: 2026-01-07 12:25:18.461742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bb37c31ff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('track_presence', sa.Boolean(), nullable=True),
    sa.Column('is_randomized_mac', sa.Boolean(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('driver_type', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('formatted_value', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_timestamp'), ['timestamp'], unique=False)

    op.create_table('presence_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presence_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_timestamp'))

    op.drop_table('event')
    op.drop_table('hardware')
    op.drop_table('device')
    # ### end Alembic commands ###
