"""Add track-presence feild

Revision ID: b4f146fa70d2
Revises: df2e04ca765e
Create Date: 2025-12-22 14:49:04.498281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f146fa70d2'
down_revision = 'df2e04ca765e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_presence', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('track_presence')

    # ### end Alembic commands ###
