"""Add presence monitoring tables

Revision ID: df2e04ca765e
Revises: 05144d9fd9f6
Create Date: 2025-12-22 12:45:23.336186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2e04ca765e'
down_revision = '05144d9fd9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('presence_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presence_event_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_event_timestamp'))

    op.drop_table('presence_event')
    op.drop_table('device')
    # ### end Alembic commands ###
