"""Initial setup migration

Revision ID: f77f533a6ec7
Revises: 
Create Date: 2026-01-15 20:29:18.837583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77f533a6ec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('last_ip', sa.String(length=15), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('is_randomized_mac', sa.Boolean(), nullable=True),
    sa.Column('track_presence', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('linked_to_device_id', sa.Integer(), nullable=True),
    sa.Column('link_confidence', sa.Float(), nullable=True),
    sa.Column('ip_history', sa.JSON(), nullable=True),
    sa.Column('mdns_services', sa.JSON(), nullable=True),
    sa.Column('device_metadata', sa.JSON(), nullable=True),
    sa.Column('typical_connection_times', sa.JSON(), nullable=True),
    sa.Column('co_occurring_devices', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['linked_to_device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_is_home'), ['is_home'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_is_randomized_mac'), ['is_randomized_mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_mac_address'), ['mac_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_track_presence'), ['track_presence'], unique=False)

    op.create_table('hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('driver_interface', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('devices_present', sa.JSON(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_snapshot_timestamp'), ['timestamp'], unique=False)

    op.create_table('device_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device1_id', sa.Integer(), nullable=False),
    sa.Column('device2_id', sa.Integer(), nullable=False),
    sa.Column('association_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_together', sa.DateTime(), nullable=True),
    sa.Column('co_occurrence_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device1_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['device2_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device1_id', 'device2_id', name='unique_device_pair')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_timestamp'), ['timestamp'], unique=False)

    op.create_table('presence_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presence_event_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_event_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_presence_event_device_id'))

    op.drop_table('presence_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_timestamp'))

    op.drop_table('event')
    op.drop_table('device_association')
    with op.batch_alter_table('network_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_snapshot_timestamp'))

    op.drop_table('network_snapshot')
    op.drop_table('hardware')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_track_presence'))
        batch_op.drop_index(batch_op.f('ix_device_mac_address'))
        batch_op.drop_index(batch_op.f('ix_device_last_seen'))
        batch_op.drop_index(batch_op.f('ix_device_is_randomized_mac'))
        batch_op.drop_index(batch_op.f('ix_device_is_home'))

    op.drop_table('device')
    # ### end Alembic commands ###
